# R for travis
# https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: false

# Temporarily enable to cache R packages
# script: true

before_install:
- openssl aes-256-cbc -K $encrypted_548ab35dca07_key -iv $encrypted_548ab35dca07_iv -in tests/testthat/token.rds.enc -out tests/testthat/token.rds -d

r:
  - bioc-release
  # - bioc-devel
r_packages:
  - covr
  - rlang

after_success:
  - Rscript -e 'covr::codecov()'
